### ISSUE TITLE
TypeError: is_file(): Argument #1 ($filename) must be of type string, SplFileInfo given in /var/www/html/lib/private/Profiler/FileProfilerStorage.php:103

### ISSUE THREAD

**Issue by come-nc** [nextcloud/profiler#194]
```
$ occ profiler:clear
An unhandled exception has been thrown:
TypeError: is_file(): Argument #1 ($filename) must be of type string, SplFileInfo given in /var/www/html/lib/private/Profiler/FileProfilerStorage.php:103
Stack trace:
#0 /var/www/html/lib/private/Profiler/FileProfilerStorage.php(103): is_file(Object(SplFileInfo))
#1 /var/www/html/lib/private/Profiler/Profiler.php(119): OC\Profiler\FileProfilerStorage->purge()
#2 /var/www/html/apps-extra/profiler/lib/Command/Clear.php(30): OC\Profiler\Profiler->clear()
#3 /var/www/html/apps-extra/photos/vendor/symfony/console/Command/Command.php(298): OCA\Profiler\Command\Clear->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/core/Command/Base.php(177): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/apps-extra/photos/vendor/symfony/console/Application.php(1040): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/apps-extra/photos/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Profiler\Command\Clear), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/apps-extra/photos/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/console.php(100): OC\Console\Application->run()
#10 /var/www/html/occ(11): require_once('/var/www/html/c...')
#11 {main}⏎       
```

**Comment by come-nc** [comment]
My bad, this was an application version mismatch problem from dev setup
